# ops/build.yaml
context_parser: pypyr.parser.keyvaluepairs

steps:
  - pypyr.steps.debug

  # Load config from ops/config.yaml (single place to customize)
  # Values from config.yaml can be overridden by CLI args
  - name: pypyr.steps.fetchyaml
    in:
      fetchYaml:
        path: ops/config.yaml

  # Set defaults if not already set (from config or CLI)
  - name: pypyr.steps.default
    in:
      defaults:
        registry: docker.io
        image_name: imprvai/imprv_pgvectorscale
        pg_version: '17'
        vectorscale_ref: '0.9.0'
        multiarch: 'false'
        push: 'false'

  - name: pypyr.steps.py
    description: Read version from Poetry
    in:
      py: |
        import subprocess
        import os

        # Pipeline runs from project root (where pyproject.toml is)
        # But if running from ops/, go up one level
        cwd = os.getcwd()
        if os.path.basename(cwd) == 'ops':
          cwd = os.path.dirname(cwd)

        result = subprocess.run(
          ['poetry', 'version', '--short'],
          cwd=cwd,
          capture_output=True,
          text=True,
        )

        if result.returncode != 0:
          raise Exception(f"poetry version failed: {result.stderr}")

        app_version = result.stdout.strip()
        tag_pg_versioned = f"{pg_version}-v{app_version}"
        tag_pg_latest = f"{pg_version}-latest"

        # Persist to context for later steps
        save('app_version', 'tag_pg_versioned', 'tag_pg_latest')

  - name: pypyr.steps.shell
    description: Build Docker image (single-arch or multi-arch based on flag)
    in:
      cmd:
        - |
          set -e

          # If running from ops/, go to project root
          if [ "$(basename "$PWD")" = "ops" ]; then
            cd ..
          fi

          GIT_SHA=$(git rev-parse --short HEAD || echo "nogit")
          BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          if [ "{multiarch}" = "true" ] || [ "{multiarch}" = "True" ]; then
            echo ">>> Building MULTI-ARCH Docker image for version {app_version}"
            echo ">>> Platforms: linux/amd64,linux/arm64"

            # Check if buildx is available
            if ! docker buildx version > /dev/null 2>&1; then
              echo "ERROR: docker buildx is required for multi-arch builds"
              echo "Install Docker Buildx or use single-arch build (default)"
              exit 1
            fi

            # Create buildx builder if it doesn't exist
            docker buildx create --name multiarch-builder --use 2>/dev/null || docker buildx use multiarch-builder || true

            # For multi-arch, we need to push (can't use --load for multi-arch)
            if [ "{push}" = "true" ]; then
              echo ">>> Pushing multi-arch images to registry"
              BUILDX_FLAGS="--push"
            else
              echo ">>> WARNING: Multi-arch builds require --push (images will be pushed to registry)"
              echo ">>> Set push=true or use single-arch build for local-only images"
              BUILDX_FLAGS="--push"
            fi

            docker buildx build \
              --platform linux/amd64,linux/arm64 \
              $BUILDX_FLAGS \
              --build-arg VECTORSCALE_REF={vectorscale_ref} \
              --build-arg APP_VERSION={app_version} \
              --build-arg VCS_REF=$GIT_SHA \
              --build-arg BUILD_DATE=$BUILD_DATE \
              -t {registry}/{image_name}:{tag_pg_versioned} \
              -t {registry}/{image_name}:{tag_pg_latest} \
              -f docker/Dockerfile \
              docker/
          else
            echo ">>> Building SINGLE-ARCH Docker image for version {app_version}"
            echo ">>> Platform: current platform only"
            echo ">>> Use multiarch=true for multi-arch builds"

            echo "Tags:"
            echo "  {registry}/{image_name}:{tag_pg_versioned}"
            echo "  {registry}/{image_name}:{tag_pg_latest}"

            docker build \
              --build-arg VECTORSCALE_REF={vectorscale_ref} \
              --build-arg APP_VERSION={app_version} \
              --build-arg VCS_REF=$GIT_SHA \
              --build-arg BUILD_DATE=$BUILD_DATE \
              -t {registry}/{image_name}:{tag_pg_versioned} \
              -t {registry}/{image_name}:{tag_pg_latest} \
              -f docker/Dockerfile \
              docker/
          fi
